<?php
/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class QuestionnaireExecutionInfo {

  static $swaggerTypes = array(
      'status' => 'string',
      'guid' => 'string',
      'collector_id' => 'float',
      'collector_guid' => 'string',
      'questionnaire_name' => 'string',
      'owner' => 'UserIdentity',
      'executive' => 'UserIdentity',
      'approver' => 'UserIdentity',
      'datasource_id' => 'float',
      'id' => 'float',
      'modified' => 'string',
      'document' => 'DocumentDownloadInfo'

    );

  public $status; // string
  public $guid; // string
  public $collector_id; // float
  public $collector_guid; // string
  public $questionnaire_name; // string
  public $owner; // UserIdentity
  public $executive; // UserIdentity
  public $approver; // UserIdentity
  public $datasource_id; // float
  public $id; // float
  public $modified; // string
  public $document; // DocumentDownloadInfo
  }

