<?php
/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class SignatureFormFieldSettingsInfo {

  static $swaggerTypes = array(
      'name' => 'string',
      'mandatory' => 'bool',
      'order' => 'int',
      'page' => 'int',
      'locationX' => 'float',
      'locationY' => 'float',
      'locationWidth' => 'float',
      'locationHeight' => 'float',
      'regularExpression' => 'string',
      'fontName' => 'string',
      'fontColor' => 'string',
      'fontSize' => 'float',
      'fontBold' => 'bool',
      'fontItalic' => 'bool',
      'fontUnderline' => 'bool',
      'forceNewField' => 'bool',
      'acceptableValues' => 'string',
      'defaultValue' => 'string',
      'tooltip' => 'string',
      'align' => 'int',
      'guidanceText' => 'string'

    );

  public $name; // string
  public $mandatory; // bool
  public $order; // int
  public $page; // int
  public $locationX; // float
  public $locationY; // float
  public $locationWidth; // float
  public $locationHeight; // float
  public $regularExpression; // string
  public $fontName; // string
  public $fontColor; // string
  public $fontSize; // float
  public $fontBold; // bool
  public $fontItalic; // bool
  public $fontUnderline; // bool
  public $forceNewField; // bool
  public $acceptableValues; // string
  public $defaultValue; // string
  public $tooltip; // string
  public $align; // int
  public $guidanceText; // string
  }

