<?php
/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class SignatureEnvelopeInfo {

  static $swaggerTypes = array(
      'id' => 'string',
      'name' => 'string',
      'creationDateTime' => 'string',
      'updatedDateTime' => 'string',
      'ownerGuid' => 'string',
      'status' => 'int',
      'statusDateTime' => 'string',
      'reminderTime' => 'float',
      'stepExpireTime' => 'float',
      'envelopeExpireTime' => 'float',
      'ownerShouldSign' => 'bool',
      'orderedSignature' => 'bool',
      'emailSubject' => 'string',
      'emailBody' => 'string',
      'documentsCount' => 'float',
      'documentsPages' => 'float',
      'recipients' => 'array[SignatureEnvelopeRecipientInfo]',
      'waterMarkText' => 'string',
      'waterMarkImage' => 'string',
      'attachSignedDocument' => 'bool',
      'includeViewLink' => 'bool',
      'canBeCommented' => 'bool',
      'inPersonSign' => 'bool',
      'ownerName' => 'string'

    );

  public $id; // string
  public $name; // string
  public $creationDateTime; // string
  public $updatedDateTime; // string
  public $ownerGuid; // string
  public $status; // int
  public $statusDateTime; // string
  public $reminderTime; // float
  public $stepExpireTime; // float
  public $envelopeExpireTime; // float
  public $ownerShouldSign; // bool
  public $orderedSignature; // bool
  public $emailSubject; // string
  public $emailBody; // string
  public $documentsCount; // float
  public $documentsPages; // float
  public $recipients; // array[SignatureEnvelopeRecipientInfo]
  public $waterMarkText; // string
  public $waterMarkImage; // string
  public $attachSignedDocument; // bool
  public $includeViewLink; // bool
  public $canBeCommented; // bool
  public $inPersonSign; // bool
  public $ownerName; // string
  }

