<?php
/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class SignatureFormInfo {

  static $swaggerTypes = array(
      'id' => 'string',
      'name' => 'string',
      'ownerGuid' => 'string',
      'templateGuid' => 'string',
      'createdTimeStamp' => 'string',
      'status' => 'int',
      'statusDateTime' => 'string',
      'documentsCount' => 'float',
      'documentsPages' => 'float',
      'participantsCount' => 'float',
      'fieldsInFinalFileName' => 'array[string]',
      'canParticipantDownloadForm' => 'bool',
      'waterMarkText' => 'string',
      'waterMarkImage' => 'string',
      'fieldsCount' => 'float',
      'notifyOwnerOnSign' => 'bool',
      'attachSignedDocument' => 'bool'

    );

  public $id; // string
  public $name; // string
  public $ownerGuid; // string
  public $templateGuid; // string
  public $createdTimeStamp; // string
  public $status; // int
  public $statusDateTime; // string
  public $documentsCount; // float
  public $documentsPages; // float
  public $participantsCount; // float
  public $fieldsInFinalFileName; // array[string]
  public $canParticipantDownloadForm; // bool
  public $waterMarkText; // string
  public $waterMarkImage; // string
  public $fieldsCount; // float
  public $notifyOwnerOnSign; // bool
  public $attachSignedDocument; // bool
  }

