<?php
/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class StorageProviderInfo {

  static $swaggerTypes = array(
      'id' => 'float',
      'provider' => 'string',
      'type' => 'string',
      'token' => 'array[int]',
      'publicKey' => 'string',
      'privateKey' => 'string',
      'rootFolder' => 'string',
      'isPrimary' => 'bool',
      'serviceHost' => 'string',
      'syncOptions' => 'string'

    );

  public $id; // float
  public $provider; // string
  public $type; // string
  public $token; // array[int]
  public $publicKey; // string
  public $privateKey; // string
  public $rootFolder; // string
  public $isPrimary; // bool
  public $serviceHost; // string
  public $syncOptions; // string
  }

