<?php
/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class SubscriptionPlanUsageInfo {

  static $swaggerTypes = array(
      'users' => 'int',
      'document_count' => 'string',
      'viewer' => 'int',
      'signature' => 'int',
      'assembly' => 'int',
      'comparison' => 'int',
      'conversion' => 'int',
      'sharing' => 'int',
      'api' => 'int',
      'branding' => 'bool',
      'max_document_size' => 'int',
      'annotation' => 'int',
      'storage_space' => 'string',
      'document_tokens' => 'int',
      'watermarking' => 'bool',
      'storage_providers' => 'bool',
      'private_storage' => 'bool',
      'embeddings' => 'int'

    );

  public $users; // int
  public $document_count; // string
  public $viewer; // int
  public $signature; // int
  public $assembly; // int
  public $comparison; // int
  public $conversion; // int
  public $sharing; // int
  public $api; // int
  public $branding; // bool
  public $max_document_size; // int
  public $annotation; // int
  public $storage_space; // string
  public $document_tokens; // int
  public $watermarking; // bool
  public $storage_providers; // bool
  public $private_storage; // bool
  public $embeddings; // int
  }

