<?php
/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class UploadRequestResult {

  static $swaggerTypes = array(
      'adj_name' => 'string',
      'url' => 'string',
      'type' => 'string',
      'file_type' => 'string',
      'size' => 'string',
      'version' => 'int',
      'view_job_id' => 'float',
      'thumbnail' => 'string',
      'id' => 'float',
      'guid' => 'string'

    );

  public $adj_name; // string
  public $url; // string
  public $type; // string
  public $file_type; // string
  public $size; // string
  public $version; // int
  public $view_job_id; // float
  public $thumbnail; // string
  public $id; // float
  public $guid; // string
  }

